Feat  pages and widgets
SolarHelper/client pull request #8
Opened 2023-10-29 14:31 UTC by frontsinfin

**1. Добавил footer.**
Сверстал footer, оформил и адаптировал.

**2. Добавил адаптив Header и переименовал в Navbar.**
![image](https://github.com/SolarHelper/client/assets/123500635/5b9a43b1-79db-4646-a3f8-a81339a70561)

**3. Добавил карточки товаров**
CardInCart:
![image](https://github.com/SolarHelper/client/assets/123500635/9183fea4-8d49-4d44-8f7f-8c228f816c12)
Cardproduct:
![image](https://github.com/SolarHelper/client/assets/123500635/cfc3adc1-a866-4848-8e5c-b37a861ce8dd)

**2. Добавил страницы-заглушки political и forIntallers.**
Ссылки на страницы в футере:
![image](https://github.com/SolarHelper/client/assets/123500635/db1a6dea-fe1b-43f0-b5ea-98863a5beff1)

2023-10-31 12:09 UTC, Gransly requested changes

2023-10-31 12:09 UTC, Gransly commented on src/app/styles/_mixins.scss
> +  flex-direction: column;
displey flex не хватает

2023-10-31 12:09 UTC, Gransly commented on src/app/styles/_mixins.scss
> +    column-gap: calc($gap * 0.5);
В дизайне так же ?

2023-10-31 12:09 UTC, Gransly commented on src/shared/ui/RaitingForm/RaitingForm.module.scss
> +  //ширина и высота decktop, ширина и высота при width<678px
Опечатка

2023-10-31 12:09 UTC, Gransly commented on src/shared/ui/RaitingForm/RaitingForm.module.scss
> +
Думаю все эти коментарии лишние, и так все понятно же)

2023-10-31 12:09 UTC, Gransly commented on src/shared/ui/RaitingForm/RaitingForm.tsx
> +interface RaitingFormProps {
добавь пробел между импортом и итерфейсом

2023-10-31 12:09 UTC, Gransly commented on src/shared/ui/buttons/Button.module.scss
> +  // 12px шрифт,при ширине 678px - 10px,line-height 1,bold
Коменты лишние

2023-10-31 12:09 UTC, Gransly commented on src/shared/ui/inputs/Input.tsx
> +      <label className="title18" htmlFor={label}>
Если label undefined, то зачем нам рендерить  <label className="title18" htmlFor={label}>
Тернарку сюда

2023-10-31 12:09 UTC, Gransly commented on src/shared/ui/inputs/input/Input.module.scss
> +  border-radius: var(--radius-normal);
Появились же миксины и переменные, че бы их не использовать

2023-10-31 12:09 UTC, Gransly commented on src/shared/ui/svg/ArrowLeftSvg.tsx
> +import * as React from "react";
1) Зачем отдельный компонент для svg ?
2) зачем 2 svg стрелки, когда ее можно отзеркалить

2023-10-31 12:09 UTC, Gransly commented on src/shared/ui/svg/ArrowLeftSvg.tsx
> +const ArrowLeftSvg = () => (
https://react-svgr.com/docs/next/ тут все написано, как настроить, я только не помню webpack ли стоит у нас 
Как то так это будет выглядеть
![image](https://github.com/SolarHelper/client/assets/58291270/11589923-f7d8-493c-b391-7297a51c92a2)

2023-10-31 12:09 UTC, Gransly commented on src/store/slice/counterSlice/counterSlice.ts
> +  // Создаем переменную для сохранения данных которые приходят c action.payload (переменных может быть сколько угодно)
Тоже что то слишком много коментариев)

2023-10-31 12:09 UTC, Gransly commented on src/widgets/CardInCart/CardInCart.tsx
> +      ></Image>
А нельзя просто ```<Image/> ```?

2023-10-31 12:09 UTC, Gransly commented on src/widgets/CardInCart/CardInCart.tsx
> +          <span className="title18">{productPrice}р </span>
Пробел нужен ?

2023-10-31 12:09 UTC, Gransly commented on src/widgets/CardProduct/CardProduct.tsx
> +interface CardProductProps {
Пробел

2023-10-31 12:09 UTC, Gransly commented on src/widgets/CardProduct/CardProduct.tsx
> +  productName,
Слишком много пропсов,  тут оставь props
А ниже 
```
{ productName, productPrice, productRaiting, NumberOfProducts } = props
```

2023-10-31 12:09 UTC, Gransly commented on src/widgets/footer/Footer.module.scss
> +  //падинги верхний, правый, левый, нижний
Хммммм, думаю что это лишнее, старайся не оставлять очевидные коментарии, они нужны только для какой-то сложной / не очевидной логики

2023-10-31 12:09 UTC, Gransly commented on src/widgets/footer/Footer.module.scss
> +  // @media (max-width: $mobile-width) {
Надо ?

2023-11-05 17:18 UTC, floweredcat commented on src/widgets/CardProduct/CardProduct.tsx
> +        <RaitingForm productRaiting={productRaiting}></RaitingForm>
Для лучшей читаемости если нет чилдренов можно использовать самозакрывающийся вызов (<Comp {...props} />)

2023-11-05 17:18 UTC, floweredcat commented on src/widgets/footer/Footer.tsx
> +          <abbr title="political">Политика конфиденциальности</abbr>
зачем abbr?

2023-11-05 17:18 UTC, floweredcat commented on src/shared/ui/counter/Counter.tsx
> +        placeholder="0"
Вместо placeholder=0 лучше сделай значение по умолчанию

2023-11-05 17:18 UTC, floweredcat commented on src/shared/ui/counter/Counter.tsx
> +      <button className={style.btn} onClick={() => dispatch(decrement())}>
Вот как раз здесь логика онклики должны получаться от родителя, потому что UI мы можем захотеть переиспользовать в другом месте где он будет показывать другое значение с другими онкликами

2023-11-05 17:18 UTC, floweredcat commented on src/shared/ui/RaitingForm/RaitingForm.tsx
> +const RaitingForm = ({ productRaiting }: RaitingFormProps) => {
raiting = рерайтинг, rating = рейтинг

2023-11-05 17:18 UTC, floweredcat commented on src/shared/ui/svg/ArrowLeftSvg.tsx
> +const ArrowLeftSvg = () => (
А почему просто не импортировать svg файл вместо создания компонентов?

2023-11-05 17:18 UTC, floweredcat commented on src/app/pages/calculator/page.tsx
> +        qwdqwd <UserIcon />
qwdqwd?

2023-11-05 17:18 UTC, floweredcat commented on src/app/pages/calculator/page.tsx
> +        cityInstallers="qdqwd"
?

2023-11-13 20:16 UTC, floweredcat commented on src/widgets/CardProduct/CardProduct.tsx
> +          decrement={() => setNumberOfProducts(numberOfProducts - 1)}
Стрелочные функции лучше вынести в переменную для лучшей читаемости, также в остальных местах

2023-11-14 17:11 UTC, merged